### PR TITLE
create `bdk.rs`  file for `BDK Wallet` project

### PR DESCRIPTION
**Pull request by 15IITian**
After having several discussion -> current goal of this pr :

 * This pr aims to create `bdk.rs` file/module in `wallet` module for working on `BDK Wallet` project
 
 * It contains all the contents of wallet module  because ->
 
 
https://github.com/citadel-tech/coinswap/pull/162#issuecomment-2144277698

### CODE REVIEW

**Comment by 15IITian** [comment]
Right now, we are skipping the idea of seperating wallet api into two modules due to some avoidable errors comming due to this architecture.

**Comment by Shourya742** [comment]
I don't think this should come as a separate PR or even an issue. Creating a file and then adding all the methods from different files doesn't make sense without a proper plan.

**Comment by 15IITian** [comment]
> Creating a file and then adding all the methods from different files doesn't make sense without a proper plan.

But this is basically done  to have some stand-alone file in which we can independently work on BDK project .
The reason of adding all contents of different files  is :
  * to have independent file for the BDK project
  * at the initial stage -> we can't just segregate/modularize  all the code before working on code changes -> thus it's better to just dump all contents in 1 file -> work on it -> after completion then try to modularize the wallet code.
  
This was discussed & suggested by @mojo in previous dev call.

**Comment by 15IITian** [comment]
I now feel , the issue of this pr  should be changed to modularize the whole wallet code after  making required code changes  in the project .
This pr will not close it .

**Comment by Shourya742** [comment]
ACK 0120e9780af946368a05f966828daae191cc8044

**Pull request merged**
