### PR TITLE
musig2 apis

### PR DESCRIPTION
**Pull request by 007harshmahajan**
currently apis are just to make interactive signing session with  `agg_signature`, `partial signature` and `nonce_gen` more will be adde accordingly depending on taproot requirments

### CODE REVIEW

**Comment by mojoX911** [comment]
@007harshmahajan any update on this? The build and lint failure seems very simple to solve.

**Comment by 007harshmahajan** [comment]
> @007harshmahajan any update on this? The build and lint failure seems very simple to solve.
will get it done today

**Comment by mojoX911** [comment]
Few more clippy fixes left.

**Comment by 007harshmahajan** [comment]
All other lint issues are fixed in master, need to rebase from master

**Review by mojoX911 — APPROVED** [review]
ACK 7c4b3ac320cf14a3b8b9cf753d900dcd061735a2

**Review by Shourya742 — CHANGES_REQUESTED** [review]
I see a merge commit from the master branch and a few unrelated commits, such as Clippy fixes. Could you remove the merge commit from the master branch and squash these non-contextual commits into a contextual one's?

**Comment by 007harshmahajan** [comment]
squashed musig code in [316d67d](https://github.com/citadel-tech/coinswap/pull/191/commits/316d67dbd009f2333c12287e92dc95806e6b4e52) and merge with master  [6f94f06](https://github.com/citadel-tech/coinswap/pull/191/commits/6f94f06d982e582c93d1ae20a51af6055317c039)

**Comment by 007harshmahajan** [comment]
cant have rebase without clumsy PR, will add code with after merge of #227

**Pull request closed without merging**
